name: Create new release based on release-log

on:
  push:
    branches:
      - main
    paths:
      - '**.json'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Release log information
        id: release-information
        run: |-
          RELEASE_VERSION=$(cat ./release-log.json | jq -r '.[0].version')
          RELEASE_DESCRIPTION=$(cat ./release-log.json | jq -r '.[0].description')
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT
          echo "release_description=$RELEASE_DESCRIPTION" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release-information.outputs.release_version }}
          release_name: ${{ steps.release-information.outputs.release_version }}
          body: ${{ steps.release-information.outputs.release_description }}
          draft: false
          prerelease: false
